# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

In [3]:
datalink='https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [4]:
data0=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data', sep='\s+' ,parse_dates=[[0,1,2]])

In [5]:
data=pd.read_csv(datalink,delim_whitespace=True,parse_dates=[['Yr','Mo','Dy']])
data

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [6]:
data.Yr_Mo_Dy.dtype

dtype('<M8[ns]')

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [7]:
def correct_year(wrong_column):
    pattern=r'^20([2-9][4-9]|[3-9][0-9])'
    wrong_column=wrong_column.astype(str)
    wrong_column=wrong_column.str.replace(pattern,r'19\1',regex=True)
    wrong_column=pd.to_datetime(wrong_column)
    return wrong_column

In [8]:
data.Yr_Mo_Dy=correct_year(data.Yr_Mo_Dy)

In [9]:
data

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [10]:
data.Yr_Mo_Dy.dtype

dtype('<M8[ns]')

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [11]:
data.set_index('Yr_Mo_Dy',inplace=True,drop=True)
data

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [12]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [13]:
# Solution 1
data.notnull().sum()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

In [14]:
# Solution 2
data.count()

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

In [15]:
#the total number of non missing values
print (f"the total number of non missing values is: {data.count().sum()}")

the total number of non missing values is: 78857

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [17]:
# The mean windspeed for all locations once
data.mean().mean()

10.227982360836924

In [16]:
# The mean windspeed for each location
data.mean()

RPT    12.362987
VAL    10.644314
ROS    11.660526
KIL     6.306468
SHA    10.455834
BIR     7.092254
DUB     9.797343
CLA     8.495053
MUL     8.493590
CLO     8.707332
BEL    13.121007
MAL    15.599079
dtype: float64

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [18]:
#first way
loc_stats=pd.DataFrame(data=(data.min(),data.max(),data.mean(),data.std()),index=['min','max','mean','standard deviation'])
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
standard deviation,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794

In [19]:
#another way
data.agg(['min','max','mean','std'])

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [20]:
day_stats=data.agg(['min','max','mean','std'],axis=1)
day_stats

             min    max       mean       std
Yr_Mo_Dy
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [21]:
data[data.index.month==1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [22]:
data.resample('Y').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-12-31,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962-12-31,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963-12-31,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964-12-31,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965-12-31,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966-12-31,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967-12-31,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968-12-31,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969-12-31,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970-12-31,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971-12-31,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972-12-31,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973-12-31,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974-12-31,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975-12-31,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976-12-31,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977-12-31,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978-12-31,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [23]:
data.groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [24]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [25]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [26]:
data_optimized=data.loc["1961-01-02":]
data_optimized

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
1961-01-06,13.21,8.12,9.96,6.67,5.37,4.50,10.67,4.42,7.17,7.50,8.12,13.17
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-12-27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
1978-12-28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
1978-12-29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
1978-12-30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
1978-12-31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

In [27]:
data_optimized.groupby(data_optimized.index.to_period('W')).agg({'min', 'max', 'mean', 'std'}).head(52)

                         RPT                                VAL         \
                         min    max       mean       std    min    max
Yr_Mo_Dy
1961-01-02/1961-01-08  10.58  18.50  13.541429  2.631321   6.63  16.88
1961-01-09/1961-01-15   9.04  19.75  12.468571  3.555392   3.54  12.08
1961-01-16/1961-01-22   4.92  19.83  13.204286  5.337402   3.42  14.37
1961-01-23/1961-01-29  13.62  25.04  19.880000  4.619061   9.96  23.91
1961-01-30/1961-02-05  10.58  24.21  16.827143  5.251408   9.46  24.21
1961-02-06/1961-02-12  16.00  24.54  19.684286  3.587677  11.54  21.42
1961-02-13/1961-02-19   6.04  22.50  15.130000  5.064609  11.63  20.17
1961-02-20/1961-02-26   7.79  25.80  15.221429  7.020716   7.08  21.50
1961-02-27/1961-03-05  10.96  13.33  12.101429  0.997721   8.83  17.00
1961-03-06/1961-03-12   4.88  14.79   9.376667  3.732263   8.08  16.96
1961-03-13/1961-03-19   4.92  16.88  11.911429  3.860036   9.46  15.54
1961-03-20/1961-03-26   6.29  15.00   9.567143  3.613298   2.58  11.63
1961-03-27/1961-04-02   5.88  18.25  10.757143  5.046922   3.50  16.29
1961-04-03/1961-04-09   4.50  18.12  11.964286  4.604392   7.04  14.62
1961-04-10/1961-04-16   4.71  15.50   8.965714  3.937727   4.83  12.25
1961-04-17/1961-04-23   4.00  21.09  12.621429  5.676655   3.71  15.41
1961-04-24/1961-04-30   4.08  16.29  10.117143  4.349662   6.50  14.46
1961-05-01/1961-05-07   9.87  23.00  15.367143  5.025507  10.29  19.79
1961-05-08/1961-05-14   3.54  12.79   7.772857  3.371022   3.96  15.12
1961-05-15/1961-05-21   4.88  15.04   8.225714  3.631730   3.58  10.17
1961-05-22/1961-05-28   4.96  11.79   8.155714  2.739433   3.67  12.50
1961-05-29/1961-06-04   7.00  15.92  10.321429  3.099701   4.75   9.79
1961-06-05/1961-06-11   8.29  14.42  10.917143  2.248597   6.83  11.54
1961-06-12/1961-06-18   6.13  14.33  10.571429  3.009482   4.12  14.54
1961-06-19/1961-06-25   4.00   9.00   7.345714  1.982035   3.25   9.50
1961-06-26/1961-07-02   7.21  13.13  10.236667  2.557856   6.34  14.37
1961-07-03/1961-07-09   7.29  17.50  11.715714  3.664855   3.75  10.75
1961-07-10/1961-07-16   8.63  22.50  16.680000  5.168710   7.87  19.29
1961-07-17/1961-07-23   3.04   5.88   4.202857  1.047978   2.92   6.79
1961-07-24/1961-07-30   6.13  16.08  10.561429  4.157641   4.63  13.79
1961-07-31/1961-08-06   7.67  16.08  10.870000  2.950887   5.09  15.79
1961-08-07/1961-08-13   2.88  14.21  10.058333  4.422268   4.42  10.00
1961-08-14/1961-08-20  13.13  18.91  15.607143  2.283635   7.25  13.62
1961-08-21/1961-08-27   7.67  18.16  12.391429  3.395857   6.87  14.58
1961-08-28/1961-09-03   3.63  14.46   8.678571  4.398615   1.13  22.00
1961-09-04/1961-09-10   5.00  17.62  10.541429  5.207278   3.04  13.59
1961-09-11/1961-09-17   5.33  28.75  17.160000  7.679190   7.12  22.08
1961-09-18/1961-09-24   6.92  10.25   8.500000  1.267399   2.92  13.62
1961-09-25/1961-10-01  10.34  23.21  16.044286  4.559572   6.96  13.62
1961-10-02/1961-10-08   3.13  16.08  11.250000  5.596710   3.63  16.96
1961-10-09/1961-10-15   3.71  17.12  10.881667  4.780675   6.13  13.25
1961-10-16/1961-10-22  10.46  28.62  19.260000  7.888314   3.75  19.46
1961-10-23/1961-10-29   4.33  26.42  16.077143  7.957637   2.75  21.25
1961-10-30/1961-11-05   5.88  15.79  11.571429  3.369201   3.96  13.46
1961-11-06/1961-11-12   5.46  16.08  10.428571  3.939811   5.50  10.75
1961-11-13/1961-11-19   7.50  15.00  10.798571  2.784358   4.21  13.00
1961-11-20/1961-11-26   5.75  14.29   9.154286  3.214368   3.29  11.79
1961-11-27/1961-12-03   7.92  23.75  12.608571  5.704669   4.67  18.71
1961-12-04/1961-12-10  10.83  23.71  17.362857  4.890152   9.21  21.37
1961-12-11/1961-12-17   9.29  21.34  14.985714  4.095106   8.63  17.62
1961-12-18/1961-12-24  11.46  24.41  15.757143  4.959717   9.79  16.13
1961-12-25/1961-12-31   5.04  20.54  13.634286  5.787783   3.08  16.04

                                              ROS         ...        CLO  \
                            mean       std    min    max  ...       mean
Yr_Mo_Dy                                                  ...
1961-01-02/1961-01-08  11.486667  3.949525   7.62  12.33  ...   8.497143
1961-01-09/1961-01-15   8.967143  3.148945   7.08  19.50  ...   7.571429
1961-01-16/1961-01-22   9.862857  3.837785   7.29  20.79  ...   8.124286
1961-01-23/1961-01-29  16.141429  5.170224  12.67  25.84  ...  15.640000
1961-01-30/1961-02-05  15.460000  5.187395   9.04  19.70  ...   9.460000
1961-02-06/1961-02-12  16.417143  3.608373  13.67  21.34  ...  14.440000
1961-02-13/1961-02-19  15.091429  3.575012   6.13  19.41  ...  13.542857
1961-02-20/1961-02-26  13.625714  5.147348   6.08  22.42  ...  12.730000
1961-02-27/1961-03-05  12.951429  2.851955   8.17  13.67  ...  12.370000
1961-03-06/1961-03-12  11.578571  3.230167   7.54  16.38  ...  10.458571
1961-03-13/1961-03-19  13.501429  2.352867   5.25  13.96  ...  11.627143
1961-03-20/1961-03-26   8.387143  3.657265   4.79  15.63  ...  11.481429
1961-03-27/1961-04-02   8.852857  4.687315   5.09  14.96  ...   9.631429
1961-04-03/1961-04-09  10.654286  2.845399   9.29  18.29  ...   7.238571
1961-04-10/1961-04-16   8.000000  2.607118   3.92  15.79  ...   6.178571
1961-04-17/1961-04-23  10.438571  4.631736   3.33  17.00  ...   9.551429
1961-04-24/1961-04-30   9.798571  2.871425   2.54  14.96  ...   6.124286
1961-05-01/1961-05-07  13.970000  3.750835   8.42  21.21  ...  11.585714
1961-05-08/1961-05-14   8.712857  3.782947   4.63  12.33  ...   7.822857
1961-05-15/1961-05-21   5.631667  2.468906   5.91  15.96  ...   7.114286
1961-05-22/1961-05-28   7.388571  3.378537   3.58  20.96  ...   7.535714
1961-05-29/1961-06-04   7.407143  1.868125   6.83  15.96  ...   9.035714
1961-06-05/1961-06-11   8.992857  1.524836   6.04  11.58  ...   8.397143
1961-06-12/1961-06-18   9.565714  3.509444   6.50  15.50  ...   9.594286
1961-06-19/1961-06-25   6.108571  2.212460   5.13  10.37  ...  11.257143
1961-06-26/1961-07-02   9.482857  2.902411   7.62  10.79  ...  10.268571
1961-07-03/1961-07-09   7.220000  2.686658   7.41  14.92  ...  10.547143
1961-07-10/1961-07-16  13.518571  3.849630   8.00  14.29  ...  10.157143
1961-07-17/1961-07-23   4.255714  1.400010   4.08  12.67  ...   6.041429
1961-07-24/1961-07-30   8.445714  3.203206   6.42  15.67  ...   9.470000
1961-07-31/1961-08-06   8.792857  3.985226   5.54  15.59  ...   8.951429
1961-08-07/1961-08-13   7.941429  2.053326   6.00  11.63  ...   7.235000
1961-08-14/1961-08-20  10.565714  2.523416   9.17  14.04  ...  12.244286
1961-08-21/1961-08-27  11.430000  3.174702   9.50  17.83  ...  12.507143
1961-08-28/1961-09-03   8.821429  7.474025   2.42  12.75  ...   8.924286
1961-09-04/1961-09-10   8.798571  4.003996   3.63  14.88  ...   7.565714
1961-09-11/1961-09-17  14.440000  5.360585   7.29  26.50  ...  14.268571
1961-09-18/1961-09-24   7.154286  3.445262   5.33  12.17  ...   6.798571
1961-09-25/1961-10-01  11.361667  2.812482   7.87  17.58  ...  11.840000
1961-10-02/1961-10-08   8.757143  5.060803   4.96  17.83  ...   7.662857
1961-10-09/1961-10-15   9.734286  2.707483   4.21  20.96  ...   9.494286
1961-10-16/1961-10-22  13.364286  5.998199   9.92  22.63  ...  16.461429
1961-10-23/1961-10-29  11.867143  6.879973   4.79  23.09  ...  12.952857
1961-10-30/1961-11-05   9.590000  3.900278   6.54  14.33  ...  11.864286
1961-11-06/1961-11-12   7.690000  2.141191   3.83  20.41  ...   6.415714
1961-11-13/1961-11-19   7.951429  3.208548   6.46  32.71  ...   6.031429
1961-11-20/1961-11-26   7.337143  3.277904   4.42  14.46  ...   9.582857
1961-11-27/1961-12-03  10.442857  5.107089   8.00  19.92  ...   7.911429
1961-12-04/1961-12-10  14.362857  4.115506   9.71  20.54  ...  12.022857
1961-12-11/1961-12-17  13.472857  3.587886   9.04  19.00  ...  11.058571
1961-12-18/1961-12-24  11.971429  2.220866   8.08  22.13  ...   7.697143
1961-12-25/1961-12-31   9.504286  4.566479   2.13  29.33  ...   7.701429

                                   BEL                                MAL  \
                            std    min    max       mean       std    min
Yr_Mo_Dy
1961-01-02/1961-01-08  1.704941   5.46  17.54  12.481429  4.349139  10.88
1961-01-09/1961-01-15  4.084293   5.25  20.71  11.125714  5.552215   5.17
1961-01-16/1961-01-22  4.783952   6.50  15.92   9.821429  3.626584   6.79
1961-01-23/1961-01-29  3.713368  14.04  27.71  20.930000  5.210726  17.50
1961-01-30/1961-02-05  2.839501   9.17  19.33  14.012857  4.210858   7.17
1961-02-06/1961-02-12  1.746749  15.21  26.38  21.832857  4.063753  17.04
1961-02-13/1961-02-19  2.531361  14.09  29.63  21.167143  5.910938  10.96
1961-02-20/1961-02-26  4.920064   9.59  23.21  16.304286  5.091162   6.67
1961-02-27/1961-03-05  1.593685  11.58  23.45  17.842857  4.332331   8.83
1961-03-06/1961-03-12  3.655113  10.21  22.71  16.701429  4.358759   5.54
1961-03-13/1961-03-19  3.099472  11.29  22.79  19.350000  3.779727  11.34
1961-03-20/1961-03-26  2.538224   8.25  21.34  14.037143  4.318069  13.13
1961-03-27/1961-04-02  3.191115   7.21  18.63  13.471429  4.179854   7.17
1961-04-03/1961-04-09  2.336182   7.62  17.16  11.712857  3.147781   7.21
1961-04-10/1961-04-16  2.161137   5.75  16.17   9.482857  3.641464   5.66
1961-04-17/1961-04-23  3.347972   6.75  19.21  13.620000  4.735096   4.96
1961-04-24/1961-04-30  2.840568   5.13  13.04   9.720000  2.948237   2.67
1961-05-01/1961-05-07  3.620819   4.79  28.08  17.548571  8.003490   3.83
1961-05-08/1961-05-14  5.460237   6.54  18.66  10.421429  3.968272   3.33
1961-05-15/1961-05-21  2.216889   6.63  12.00   9.624286  1.975853   5.91
1961-05-22/1961-05-28  2.575661   6.13  14.33  10.518571  3.024524   8.00
1961-05-29/1961-06-04  2.096989   8.71  17.00  12.298571  2.611139  10.63
1961-06-05/1961-06-11  2.158323   5.37  16.17  10.148571  3.993062   5.96
1961-06-12/1961-06-18  3.792400   7.29  25.25  15.351429  6.477887   6.13
1961-06-19/1961-06-25  2.286218  11.00  19.08  14.370000  2.498386  13.75
1961-06-26/1961-07-02  1.564144   6.96  21.87  14.535714  6.303747   8.50
1961-07-03/1961-07-09  3.657179   7.08  20.41  12.220000  4.537988  12.08
1961-07-10/1961-07-16  3.271899   5.04  20.25  13.520000  4.971060   5.96
1961-07-17/1961-07-23  1.439785   4.21  10.13   7.524286  2.050218   5.41
1961-07-24/1961-07-30  4.350268   7.87  22.17  12.841429  5.580903   6.13
1961-07-31/1961-08-06  2.903018   6.17  18.54  11.595714  4.901377   9.08
1961-08-07/1961-08-13  2.073777   5.88  14.29  10.934286  2.931302   5.88
1961-08-14/1961-08-20  2.730237   9.59  21.92  14.922857  4.086725  13.04
1961-08-21/1961-08-27  3.855302   5.75  23.38  16.251429  6.711322   8.29
1961-08-28/1961-09-03  3.993736   4.79  24.71  13.664286  7.678051   5.41
1961-09-04/1961-09-10  3.649278   5.41  15.83  10.700000  4.220584   3.37
1961-09-11/1961-09-17  5.128338  13.92  23.91  19.878571  4.464252  14.67
1961-09-18/1961-09-24  2.354092   4.54  20.96  11.018571  5.235868   5.25
1961-09-25/1961-10-01  3.908397   7.79  21.37  16.208571  5.091268   4.04
1961-10-02/1961-10-08  4.296870   4.79  17.83   8.810000  4.800403   4.83
1961-10-09/1961-10-15  3.569308   8.54  20.46  14.451429  4.113200  10.75
1961-10-16/1961-10-22  5.890511  10.88  24.71  17.477143  5.645871  13.46
1961-10-23/1961-10-29  6.277629   8.50  27.29  15.592857  7.056150   9.83
1961-10-30/1961-11-05  2.784450  10.29  20.17  16.322857  4.038493  13.37
1961-11-06/1961-11-12  2.843518   6.13  12.58   9.208571  2.532196   5.71
1961-11-13/1961-11-19  4.402588   0.71   9.59   5.875714  3.643285   2.00
1961-11-20/1961-11-26  2.747452   6.50  20.46  11.772857  5.407223   4.25
1961-11-27/1961-12-03  3.680477   5.50  19.04  11.464286  5.552648   5.88
1961-12-04/1961-12-10  4.156207  10.71  21.79  15.975714  4.667933   7.58
1961-12-11/1961-12-17  4.633398   5.50  22.83  15.112857  6.531043   6.50
1961-12-18/1961-12-24  4.637096   5.29  17.67   9.958571  5.065308   2.62
1961-12-25/1961-12-31  3.526625   3.75  13.21   9.697143  3.262217   6.63


                         max       mean       std
Yr_Mo_Dy
1961-01-02/1961-01-08  16.46  13.238571  1.773062
1961-01-09/1961-01-15  16.92  11.024286  4.692355
1961-01-16/1961-01-22  17.96  11.434286  4.237239
1961-01-23/1961-01-29  27.63  22.530000  3.874721
1961-01-30/1961-02-05  19.25  11.935714  4.336104
1961-02-06/1961-02-12  21.84  19.155714  1.828705
1961-02-13/1961-02-19  22.58  16.584286  4.685377
1961-02-20/1961-02-26  23.87  14.322857  6.182283
1961-02-27/1961-03-05  17.54  13.951667  3.021387
1961-03-06/1961-03-12  22.54  14.420000  5.769890
1961-03-13/1961-03-19  22.95  16.227143  4.331958
1961-03-20/1961-03-26  22.50  18.134286  3.701846
1961-03-27/1961-04-02  19.58  13.900000  3.924555
1961-04-03/1961-04-09  15.34  11.371429  2.598271
1961-04-10/1961-04-16  12.87   8.690000  2.747842
1961-04-17/1961-04-23  20.46  12.470000  5.908542
1961-04-24/1961-04-30  17.50   8.637143  5.108365
1961-05-01/1961-05-07  26.58  14.571429  7.728504
1961-05-08/1961-05-14  26.30  10.382857  7.858246
1961-05-15/1961-05-21  14.96  10.612857  3.310819
1961-05-22/1961-05-28  17.04  11.697143  3.811818
1961-05-29/1961-06-04  17.96  13.597143  2.593586
1961-06-05/1961-06-11  19.83  12.250000  4.925055
1961-06-12/1961-06-18  24.71  15.025714  6.242673
1961-06-19/1961-06-25  21.50  17.410000  3.063011
1961-06-26/1961-07-02  16.79  12.133333  3.652313
1961-07-03/1961-07-09  21.29  15.987143  3.665705
1961-07-10/1961-07-16  21.96  12.524286  4.974273
1961-07-17/1961-07-23  10.92   8.415714  2.133994
1961-07-24/1961-07-30  25.37  13.761429  6.664574
1961-07-31/1961-08-06  20.25  13.760000  4.448251
1961-08-07/1961-08-13  15.16  10.125714  3.356585
1961-08-14/1961-08-20  24.30  16.626667  3.934238
1961-08-21/1961-08-27  22.29  16.485714  4.947608
1961-08-28/1961-09-03  22.54  11.022857  6.308087
1961-09-04/1961-09-10  20.25  11.034286  6.049619
1961-09-11/1961-09-17  33.09  18.984286  6.332885
1961-09-18/1961-09-24  14.62   9.814286  3.113507
1961-09-25/1961-10-01  17.16  13.338571  4.696504
1961-10-02/1961-10-08  19.62  11.410000  5.462002
1961-10-09/1961-10-15  21.04  15.260000  4.098130
1961-10-16/1961-10-22  33.45  23.641429  7.468377
1961-10-23/1961-10-29  30.88  18.404286  8.340881
1961-10-30/1961-11-05  23.58  19.195714  3.870800
1961-11-06/1961-11-12  15.54  10.858571  3.690752
1961-11-13/1961-11-19  13.25   5.737143  3.787654
1961-11-20/1961-11-26  22.58  12.732857  6.475867
1961-11-27/1961-12-03  21.29  14.725714  5.233192
1961-12-04/1961-12-10  29.33  16.241429  7.345893
1961-12-11/1961-12-17  21.12  14.644286  5.665006
1961-12-18/1961-12-24  16.62   8.164286  5.048035
1961-12-25/1961-12-31  15.21  12.840000  3.012729

[52 rows x 48 columns]